### ISSUE TITLE
build fails on Ubunto foacl as well as jammy

### ISSUE THREAD

**Issue by jelmd** [facebookincubator/below#8168]
Building below on Ubuntu 20.04 (focal) as well as 22.04 (jammy) fails with:

```
> cargo build --release
warning: /export/scratch/elkner/build/below/below/store/Cargo.toml: version requirement `5.0.1+zstd.1.5.2` for dependency `zstd-safe` includes semver metadata which will be ignored, removing the metadata is recommended to avoid confusion
warning: /export/scratch/elkner/build/below/below/store/Cargo.toml: version requirement `0.11.1+zstd.1.5.2` for dependency `zstd` includes semver metadata which will be ignored, removing the metadata is recommended to avoid confusion
   Compiling below v0.6.2 (/export/scratch/elkner/build/below/below)
   Compiling below-store v0.6.2 (/export/scratch/elkner/build/below/below/store)
   Compiling below-render v0.6.2 (/export/scratch/elkner/build/below/below/render)
   Compiling below-view v0.6.2 (/export/scratch/elkner/build/below/below/view)
   Compiling below-dump v0.6.2 (/export/scratch/elkner/build/below/below/dump)
error: failed to run custom build command for `below v0.6.2 (/export/scratch/elkner/build/below/below)`

Caused by:
  process didn't exit successfully: `/export/scratch/elkner/build/below/target/release/build/below-7b509743ed83d54a/build-script-build` (exit status: 101)
  --- stderr
  Warning: unrecognized map: .maps
  Warning: unrecognized map: license
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Generate("Failed to generate skeleton for /tmp/.tmpmPLpsb/exitstat.o: Failed to spawn rustfmt")', below/build.rs:36:10
  stack backtrace:
     0:     0x556421e5de2c - std::backtrace_rs::backtrace::libunwind::trace::h76d34c316a8bb75b
                                 at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
     1:     0x556421e5de2c - std::backtrace_rs::backtrace::trace_unsynchronized::hb782d75313085067
                                 at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:     0x556421e5de2c - std::sys_common::backtrace::_print_fmt::hee022c31c5bcfcc1
                                 at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/std/src/sys_common/backtrace.rs:66:5
     3:     0x556421e5de2c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h054c846eb7f0e1fb
                                 at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/std/src/sys_common/backtrace.rs:45:22
     4:     0x556421e7f80e - core::fmt::write::hcef9c23bf27d039c
                                 at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/core/src/fmt/mod.rs:1194:17
     5:     0x556421e48041 - std::io::Write::write_fmt::h6f6e0727690d342c
                                 at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/std/src/io/mod.rs:1655:15
     6:     0x556421e4ac45 - std::sys_common::backtrace::_print::h591ece144505a7d5
                                 at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/std/src/sys_common/backtrace.rs:48:5
     7:     0x556421e4ac45 - std::sys_common::backtrace::print::hbdcd241dc6539260
                                 at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/std/src/sys_common/backtrace.rs:35:9
     8:     0x556421e4ac45 - std::panicking::default_hook::{{closure}}::hc934c90a9f702809
                                 at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/std/src/panicking.rs:295:22
     9:     0x556421e4a8f9 - std::panicking::default_hook::h984be39605172602
                                 at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/std/src/panicking.rs:314:9
    10:     0x556421e4b28f - std::panicking::rust_panic_with_hook::h04be8cf992436914
                                 at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/std/src/panicking.rs:698:17
    11:     0x556421e5e167 - std::panicking::begin_panic_handler::{{closure}}::h47ebda0479239463
                                 at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/std/src/panicking.rs:588:13
    12:     0x556421e5df44 - std::sys_common::backtrace::__rust_end_short_backtrace::h1690aafc8ab8529a
                                 at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/std/src/sys_common/backtrace.rs:138:18
    13:     0x556421e4ada2 - rust_begin_unwind
                                 at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/std/src/panicking.rs:584:5
    14:     0x556421c609b3 - core::panicking::panic_fmt::h8531284c14f462dc
                                 at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/core/src/panicking.rs:143:14
    15:     0x556421c60a43 - core::result::unwrap_failed::h6972a430d3981bcd
                                 at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/core/src/result.rs:1785:5
    16:     0x556421c61912 - core::result::Result<T,E>::unwrap::hb6712249d2833527
    17:     0x556421c6151e - build_script_build::main::h444f38e0706d0359
    18:     0x556421c61b03 - core::ops::function::FnOnce::call_once::hcba44e2289eae45f
    19:     0x556421c616c9 - std::sys_common::backtrace::__rust_begin_short_backtrace::h0a511523a6f97bc6
    20:     0x556421c60d09 - std::rt::lang_start::{{closure}}::h045e314370c806a1
    21:     0x556421e45d81 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::he815eb44dc8530a2
                                 at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/core/src/ops/function.rs:259:13
    22:     0x556421e45d81 - std::panicking::try::do_call::h65588aa29098f6c1
                                 at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/std/src/panicking.rs:492:40
    23:     0x556421e45d81 - std::panicking::try::haa10bca2f4952c44
                                 at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/std/src/panicking.rs:456:19
    24:     0x556421e45d81 - std::panic::catch_unwind::h1d908ddce340475e
                                 at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/std/src/panic.rs:137:14
    25:     0x556421e45d81 - std::rt::lang_start_internal::{{closure}}::hdf74d953ee81ad25
                                 at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/std/src/rt.rs:128:48
    26:     0x556421e45d81 - std::panicking::try::do_call::hac535a1b96e92d37
                                 at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/std/src/panicking.rs:492:40
    27:     0x556421e45d81 - std::panicking::try::hcc24ddbc174e7e92
                                 at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/std/src/panicking.rs:456:19
    28:     0x556421e45d81 - std::panic::catch_unwind::h4b14c208c01d9f23
                                 at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/std/src/panic.rs:137:14
    29:     0x556421e45d81 - std::rt::lang_start_internal::heef479cc3aa3b396
                                 at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/std/src/rt.rs:128:20
    30:     0x556421c60cf1 - std::rt::lang_start::had5835b9e151f469
    31:     0x556421c615d3 - main
    32:     0x7f9047436d90 - <unknown>
    33:     0x7f9047436e40 - __libc_start_main
    34:     0x556421c60c05 - _start
    35:                0x0 - <unknown>
warning: build failed, waiting for other jobs to finish...
warning: unused `Result` that must be used
   --> below/view/src/lib.rs:224:13
    |
224 | /             screens
225 | |                 .get_mut()
226 | |                 .screen_mut()
227 | |                 .unwrap()
228 | |                 .take_focus(cursive::direction::Direction::none());
    | |___________________________________________________________________^
    |
    = note: `#[warn(unused_must_use)]` on by default
    = note: this `Result` may be an `Err` variant, which should be handled

warning: `below-view` (lib) generated 1 warning
    Building [=======================> ] 333/335: below-store                 
142.436u 2.734s 0:54.00 268.8%	0+0k 17758+55902io 6034pf+0w
```

**Comment by jelmd** [comment]
Not at this time (just applied the line from docs/building.md).

Installing the rustfmt package as well solved the problem, thanx.

**Comment by brianc118** [comment]
Great. I just added a bit more about the rustfmt dependency on docs/building.md

**Comment by jelmd** [comment]
```
> rustup component add rustfmt
rustup: Command not found.
```

I just did an `apt install rustfmt`.

**Comment by brianc118** [comment]
Yeah if you didn't use rustup, apt install rustfmt is fine. I believe if you use rustup that's the recommended way to install rustfmt
